### PR TITLE
Handle spaces within user or group names

### PR DESCRIPTION
**Pull request by mdhowle**
Fixes issue #7

### CODE REVIEW

**Comment by sustrik** [comment]
Uxy is meant to provide the data exposed by the tools rather then replace them. It thus shouldn't resolve numeric user IDs.

What system are you on btw? I've tried to create a user with space in the name on linux, but adduser refused to create it.

Anway, I suspect -b might properly escape the spaces is user names. Can you crun `ls -lb` and paste the output here?

**Comment by mdhowle** [comment]
I understand uxy's purpose. Unfortunately, `ls` output does not give enough details.  I mentioned this in the issue #7, but `-b` only escapes the file name.

```bash
test user@backfire:~/testing$ ls -lb
total 0
-rw-r--r-- 1 test user matthew 0 May 30 13:22 a
-rw-r--r-- 1 test user matthew 0 May 30 13:22 this\ is\ a\ file\ with\ spaces
```
I'm on Debian Linux 9.  The accounts are on a LDAP server, which is why it can have spaces.  This isn't an unusual setup.   You can fake a user with a space by manually adding a line in /etc/passwd.

`test user:x:1001:1000:Test User,,,:/tmp:/bin/bash`

**Comment by mdhowle** [comment]
Resolving the uid/gid from `ls -ln` gets it back to parity with `ls -l` without ambiguity of the user and group names.

  If the user wants the uid or gid instead, the code respects that and does not resolve and outputs like `ls -n` would.

**Comment by sustrik** [comment]
Ok, understood. Merged and thanks!

**Pull request merged**
